In [1]:
import numpy as np 

In [2]:
l = [1,2,3,4]

In [3]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [8]:
5+np.zeros((3,3))

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [9]:
5+np.ones((3,3))

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [11]:
np.empty((3,4))

array([[8.16751300e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.37961302e-306, 1.91662218e-076, 1.13806662e-042,
        8.00523454e+169],
       [9.04581620e-067, 2.19209251e-056, 3.69702436e-033,
        3.21741849e-057]])

In [12]:
np.linspace(2,5)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [13]:
np.linspace(2,5,10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [17]:
np.linspace(2,5).reshape(10,5)

array([[2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796],
       [2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041],
       [2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286],
       [2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531],
       [3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776],
       [3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ],
       [3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265],
       [4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ],
       [4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755],
       [4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ]])

In [18]:
np.linspace(2,5,endpoint = False).reshape(10,5)

array([[2.  , 2.06, 2.12, 2.18, 2.24],
       [2.3 , 2.36, 2.42, 2.48, 2.54],
       [2.6 , 2.66, 2.72, 2.78, 2.84],
       [2.9 , 2.96, 3.02, 3.08, 3.14],
       [3.2 , 3.26, 3.32, 3.38, 3.44],
       [3.5 , 3.56, 3.62, 3.68, 3.74],
       [3.8 , 3.86, 3.92, 3.98, 4.04],
       [4.1 , 4.16, 4.22, 4.28, 4.34],
       [4.4 , 4.46, 4.52, 4.58, 4.64],
       [4.7 , 4.76, 4.82, 4.88, 4.94]])

In [19]:
np.linspace(2,5,endpoint = False,retstep=True)

(array([2.  , 2.06, 2.12, 2.18, 2.24, 2.3 , 2.36, 2.42, 2.48, 2.54, 2.6 ,
        2.66, 2.72, 2.78, 2.84, 2.9 , 2.96, 3.02, 3.08, 3.14, 3.2 , 3.26,
        3.32, 3.38, 3.44, 3.5 , 3.56, 3.62, 3.68, 3.74, 3.8 , 3.86, 3.92,
        3.98, 4.04, 4.1 , 4.16, 4.22, 4.28, 4.34, 4.4 , 4.46, 4.52, 4.58,
        4.64, 4.7 , 4.76, 4.82, 4.88, 4.94]),
 0.06)

In [24]:
a = np.arange(4,40).reshape(3,6,2)

In [25]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [26]:
a.max(axis = 0)

array([[28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [27]:
a.max(axis = 1)

array([[14, 15],
       [26, 27],
       [38, 39]])

In [34]:
b = np.arange(4,40).reshape(6,6)

In [35]:
b

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [37]:
10 + b 

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [38]:
b/0

C:\Users\khana\AppData\Local\Temp\ipykernel_1792\2933543726.py:1: RuntimeWarning: divide by zero encountered in divide
  b/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [40]:
b ** 2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [41]:
pow(b,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [51]:
c = np.array([2,3,1,2,3,2]).T

In [45]:
b+c

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [46]:
b

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [47]:
c

array([2, 3, 1, 2, 3, 2])

In [48]:
b + c


array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [49]:
c.T

array([2, 3, 1, 2, 3, 2])

In [52]:
b + c

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [58]:
c = c.reshape(1,-1)

In [59]:
c

array([[2, 3, 1, 2, 3, 2]])

In [60]:
c.T

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [62]:
b + c.T

array([[ 6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18],
       [17, 18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41]])

In [63]:
b

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [64]:
np.sqrt(b)

array([[2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569],
       [4.69041576, 4.79583152, 4.89897949, 5.        , 5.09901951,
        5.19615242],
       [5.29150262, 5.38516481, 5.47722558, 5.56776436, 5.65685425,
        5.74456265],
       [5.83095189, 5.91607978, 6.        , 6.08276253, 6.164414  ,
        6.244998  ]])

In [65]:
np.exp(b)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09],
       [3.58491285e+09, 9.74480345e+09, 2.64891221e+10, 7.20048993e+10,
        1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16]])

In [66]:
#deep copy and shallow copy
#shallow
x = np.array([1,2,3])
y = x

In [67]:
#Deep
z = np.copy(x)

In [68]:
x[0] = 100

In [69]:
y

array([100,   2,   3])

In [70]:
z

array([1, 2, 3])

In [71]:
id(x)

1653167462832

In [72]:
id(y)

1653167462832

In [73]:
id(z)

1653167464560

In [74]:
id(x[0])

1653165946320

In [75]:
id(y[0])

1653165946576

In [76]:
id(x[0]) == id(y[0])

True